language: generic
sudo: required
services:
  - docker
env:
  - APP_ENV="$APP_ENV"
  - PORT="$PORT"
  - MONGO_URI="$MONGO_URI"
  - MONGO_DATABASE_NAME="$MONGO_DATABASE_NAME"
  - JWT_SECRET_KEY="$JWT_SECRET_KEY"
  - JWT_EXPIRE_TIME="$JWT_EXPIRE_TIME"

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "goginhandler"
  env: "Goginhandler-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-136250849232"
  bucket_path: "goginhandler"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
